// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/proto/pricing.proto

package pricing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OddsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OddsRequest) Reset() {
	*x = OddsRequest{}
	mi := &file_internal_proto_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OddsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OddsRequest) ProtoMessage() {}

func (x *OddsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OddsRequest.ProtoReflect.Descriptor instead.
func (*OddsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *OddsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type UpdateOddsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	HomeOdds      float64                `protobuf:"fixed64,2,opt,name=home_odds,json=homeOdds,proto3" json:"home_odds,omitempty"`
	AwayOdds      float64                `protobuf:"fixed64,3,opt,name=away_odds,json=awayOdds,proto3" json:"away_odds,omitempty"`
	DrawOdds      float64                `protobuf:"fixed64,4,opt,name=draw_odds,json=drawOdds,proto3" json:"draw_odds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOddsRequest) Reset() {
	*x = UpdateOddsRequest{}
	mi := &file_internal_proto_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOddsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOddsRequest) ProtoMessage() {}

func (x *UpdateOddsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOddsRequest.ProtoReflect.Descriptor instead.
func (*UpdateOddsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOddsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateOddsRequest) GetHomeOdds() float64 {
	if x != nil {
		return x.HomeOdds
	}
	return 0
}

func (x *UpdateOddsRequest) GetAwayOdds() float64 {
	if x != nil {
		return x.AwayOdds
	}
	return 0
}

func (x *UpdateOddsRequest) GetDrawOdds() float64 {
	if x != nil {
		return x.DrawOdds
	}
	return 0
}

type OddsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	HomeOdds      float64                `protobuf:"fixed64,2,opt,name=home_odds,json=homeOdds,proto3" json:"home_odds,omitempty"`
	AwayOdds      float64                `protobuf:"fixed64,3,opt,name=away_odds,json=awayOdds,proto3" json:"away_odds,omitempty"`
	DrawOdds      float64                `protobuf:"fixed64,4,opt,name=draw_odds,json=drawOdds,proto3" json:"draw_odds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OddsResponse) Reset() {
	*x = OddsResponse{}
	mi := &file_internal_proto_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OddsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OddsResponse) ProtoMessage() {}

func (x *OddsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OddsResponse.ProtoReflect.Descriptor instead.
func (*OddsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *OddsResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OddsResponse) GetHomeOdds() float64 {
	if x != nil {
		return x.HomeOdds
	}
	return 0
}

func (x *OddsResponse) GetAwayOdds() float64 {
	if x != nil {
		return x.AwayOdds
	}
	return 0
}

func (x *OddsResponse) GetDrawOdds() float64 {
	if x != nil {
		return x.DrawOdds
	}
	return 0
}

var File_internal_proto_pricing_proto protoreflect.FileDescriptor

const file_internal_proto_pricing_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/pricing.proto\x12\apricing\"(\n" +
	"\vOddsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x85\x01\n" +
	"\x11UpdateOddsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\thome_odds\x18\x02 \x01(\x01R\bhomeOdds\x12\x1b\n" +
	"\taway_odds\x18\x03 \x01(\x01R\bawayOdds\x12\x1b\n" +
	"\tdraw_odds\x18\x04 \x01(\x01R\bdrawOdds\"\x80\x01\n" +
	"\fOddsResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\thome_odds\x18\x02 \x01(\x01R\bhomeOdds\x12\x1b\n" +
	"\taway_odds\x18\x03 \x01(\x01R\bawayOdds\x12\x1b\n" +
	"\tdraw_odds\x18\x04 \x01(\x01R\bdrawOdds2\x89\x01\n" +
	"\x0ePricingService\x126\n" +
	"\aGetOdds\x12\x14.pricing.OddsRequest\x1a\x15.pricing.OddsResponse\x12?\n" +
	"\n" +
	"UpdateOdds\x12\x1a.pricing.UpdateOddsRequest\x1a\x15.pricing.OddsResponseB8Z6github.com/liamharvey112/betstream/internal/pb/pricingb\x06proto3"

var (
	file_internal_proto_pricing_proto_rawDescOnce sync.Once
	file_internal_proto_pricing_proto_rawDescData []byte
)

func file_internal_proto_pricing_proto_rawDescGZIP() []byte {
	file_internal_proto_pricing_proto_rawDescOnce.Do(func() {
		file_internal_proto_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_pricing_proto_rawDesc), len(file_internal_proto_pricing_proto_rawDesc)))
	})
	return file_internal_proto_pricing_proto_rawDescData
}

var file_internal_proto_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_pricing_proto_goTypes = []any{
	(*OddsRequest)(nil),       // 0: pricing.OddsRequest
	(*UpdateOddsRequest)(nil), // 1: pricing.UpdateOddsRequest
	(*OddsResponse)(nil),      // 2: pricing.OddsResponse
}
var file_internal_proto_pricing_proto_depIdxs = []int32{
	0, // 0: pricing.PricingService.GetOdds:input_type -> pricing.OddsRequest
	1, // 1: pricing.PricingService.UpdateOdds:input_type -> pricing.UpdateOddsRequest
	2, // 2: pricing.PricingService.GetOdds:output_type -> pricing.OddsResponse
	2, // 3: pricing.PricingService.UpdateOdds:output_type -> pricing.OddsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_pricing_proto_init() }
func file_internal_proto_pricing_proto_init() {
	if File_internal_proto_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_pricing_proto_rawDesc), len(file_internal_proto_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_pricing_proto_goTypes,
		DependencyIndexes: file_internal_proto_pricing_proto_depIdxs,
		MessageInfos:      file_internal_proto_pricing_proto_msgTypes,
	}.Build()
	File_internal_proto_pricing_proto = out.File
	file_internal_proto_pricing_proto_goTypes = nil
	file_internal_proto_pricing_proto_depIdxs = nil
}
