// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bet struct {
	ID        string  `json:"id"`
	UserID    string  `json:"userId"`
	EventID   string  `json:"eventId"`
	Amount    float64 `json:"amount"`
	Odds      float64 `json:"odds"`
	Status    string  `json:"status"`
	CreatedAt string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}
